Makefile: fix broken refresh target, need to also specify --output-dir
Looks like nbconvert changed, --output alone was working fine in commit 6f86e577b2859da9601447035363e30436e60456.

Fix the following error (repeated output dir), see comment https://github.com/Ouranosinc/raven/pull/393#issuecomment-860952912:
```
[NbConvertApp] Converting notebook docs/source/notebooks/Extract_geographical_watershed_properties.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
[NbConvertApp] Writing 144740 bytes to docs/source/notebooks/docs/source/notebooks/Extract_geographical_watershed_properties.ipynb
Traceback (most recent call last):
  File "/home/my_user/miniconda3/envs/raven-dev1/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 490, in convert_single_notebook
    write_results = self.write_single_notebook(output, resources)
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 450, in write_single_notebook
    write_results = self.writer.write(
  File "/home/my_user/miniconda3/envs/raven-dev1/lib/python3.8/site-packages/nbconvert/writers/files.py", line 126, in write
    with io.open(dest, 'w', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'docs/source/notebooks/docs/source/notebooks/Extract_geographical_watershed_properties.ipynb'
```

Test:

```
$ make docs/source/notebooks/Extract_geographical_watershed_properties.ipynb.refresh
Refreshing notebook docs/source/notebooks/Extract_geographical_watershed_properties.ipynb
make[1]: Entering directory '/zstore/repos/raven'
bash -c 'WPS_URL="http://0.0.0.0:9099" FINCH_WPS_URL="https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps" FLYINGPIGEON_WPS_URL="https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps" jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=240 --output "docs/source/notebooks/Extract_geographical_watershed_properties.ipynb" --output-dir . "docs/source/notebooks/Extract_geographical_watershed_properties.ipynb"; sed -i "s@http://0.0.0.0:9099/outputs/@https://pavics.ouranos.ca/wpsoutputs/@g" "docs/source/notebooks/Extract_geographical_watershed_properties.ipynb"'
[NbConvertApp] Converting notebook docs/source/notebooks/Extract_geographical_watershed_properties.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3

(...)

2021-06-15 20:02:02,768 - PYWPS - ERROR - Exception: code: 400, description: service, locator: service
NoneType: None
2021-06-15 20:02:02,768 - werkzeug - INFO - 127.0.0.1 - - [15/Jun/2021 20:02:02] "GET /outputs/13c00c32-ce36-11eb-8da2-3417ebcfda20/clipped_gb9hiqxd.tiff.msk HTTP/1.1" 400 -
2021-06-15 20:02:02,769 - PYWPS - ERROR - Exception: code: 405, description: The method is not allowed for the requested URL., locator:
Traceback (most recent call last):
  File "/home/lvu/.conda/envs/raven/lib/python3.9/site-packages/pywps/app/Service.py", line 284, in call
    wps_request = WPSRequest(http_request)
  File "/home/lvu/.conda/envs/raven/lib/python3.9/site-packages/pywps/app/WPSRequest.py", line 46, in __init__
    request_parser = self._get_request_parser_method(http_request.method)
  File "/home/lvu/.conda/envs/raven/lib/python3.9/site-packages/pywps/app/WPSRequest.py", line 56, in _get_request_parser_method
    raise MethodNotAllowed()
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
2021-06-15 20:02:02,770 - werkzeug - INFO - 127.0.0.1 - - [15/Jun/2021 20:02:02] "HEAD /outputs/13c00c32-ce36-11eb-8da2-3417ebcfda20/clipped_gb9hiqxd.tiff.MSK HTTP/1.1" 405 -
2021-06-15 20:02:02,770 - PYWPS - ERROR - Exception: code: 400, description: service, locator: service
NoneType: None
2021-06-15 20:02:02,771 - werkzeug - INFO - 127.0.0.1 - - [15/Jun/2021 20:02:02] "GET /outputs/13c00c32-ce36-11eb-8da2-3417ebcfda20/clipped_gb9hiqxd.tiff.MSK HTTP/1.1" 400 -
[NbConvertApp] Writing 144697 bytes to ./docs/source/notebooks/Extract_geographical_watershed_properties.ipynb
make[1]: Leaving directory '/zstore/repos/raven'

=====

$ make refresh-notebooks
Refresh all notebook outputs under docs/source/notebooks
bash -c 'for nb in /zstore/repos/raven/docs/source/notebooks/*.ipynb; do make -f Makefile refresh-notebooks-impl NB_REFRESH_FILE="$nb"; done; cd /zstore/repos/raven'
make[1]: Entering directory '/zstore/repos/raven'
bash -c 'WPS_URL="http://0.0.0.0:9099" FINCH_WPS_URL="https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps" FLYINGPIGEON_WPS_URL="https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps" jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=240 --output "/zstore/repos/raven/docs/source/notebooks/Assess_probabilistic_flood_risk.ipynb" --output-dir . "/zstore/repos/raven/docs/source/notebooks/Assess_probabilistic_flood_risk.ipynb"; sed -i "s@http://0.0.0.0:9099/outputs/@https://pavics.ouranos.ca/wpsoutputs/@g" "/zstore/repos/raven/docs/source/notebooks/Assess_probabilistic_flood_risk.ipynb"'
[NbConvertApp] Converting notebook /zstore/repos/raven/docs/source/notebooks/Assess_probabilistic_flood_risk.ipynb to notebook

(...)

[NbConvertApp] Writing 144845 bytes to /zstore/repos/raven/docs/source/notebooks/Assess_probabilistic_flood_risk.ipynb
make[1]: Leaving directory '/zstore/repos/raven'
make[1]: Entering directory '/zstore/repos/raven'
bash -c 'WPS_URL="http://0.0.0.0:9099" FINCH_WPS_URL="https://pavics.ouranos.ca/twitcher/ows/proxy/finch/wps" FLYINGPIGEON_WPS_URL="https://pavics.ouranos.ca/twitcher/ows/proxy/flyingpigeon/wps" jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=240 --output "/zstore/repos/raven/docs/source/notebooks/Climatological_ESP_forecasting.ipynb" --output-dir . "/zstore/repos/raven/docs/source/notebooks/Climatological_ESP_forecasting.ipynb"; sed -i "s@http://0.0.0.0:9099/outputs/@https://pavics.ouranos.ca/wpsoutputs/@g" "/zstore/repos/raven/docs/source/notebooks/Climatological_ESP_forecasting.ipynb"'
[NbConvertApp] Converting notebook /zstore/repos/raven/docs/source/notebooks/Climatological_ESP_forecasting.ipynb to notebook

(...)

```