doc: monkeypatch numpy.pi constant because numpy is mocked
  File "/home/lvu/.conda/envs/raven-docs/lib/python3.6/site-packages/properscoring/_crps.py", line 9, in <module>
    _normconst = 1.0 / np.sqrt(2.0 * np.pi)
TypeError: unsupported operand type(s) for *: 'float' and 'pi'