.travis.yml: set FLYINGPIGEON_WPS_URL to the production one because we do not launch a local FP on TravisCI build
Fix this error on TravisCI:

MaxRetryError: HTTPConnectionPool(host='localhost', port=8093): Max retries exceeded with url: /?service=WPS&request=GetCapabilities&version=1.0.0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3846780668>: Failed to establish a new connection: [Errno 111] Connection refused',))