doc: add xskillscore to environment-docs.yml
Warning, treated as error:
autodoc: failed to import process 'processes.RavenProcess' from module 'raven'; the following exception was raised:
No module named 'xskillscore'
Makefile:23: recipe for target 'html' failed

Could not mock import xskillscore because of

import xskillscore as xs

  File "/repos/raven/raven/processes/wps_forecast_evaluation.py", line 13, in <module>
    all_metrics = xs.core.deterministic.__all__ + xs.core.probabilistic.__all__
TypeError: unsupported operand type(s) for +: '__all__' and '__all__'