docker: fix missing raven binaries in docker image
Broke `make test-notebooks`, logs from `docker logs raven`:

```
Traceback (most recent call last):
  File "/opt/conda/envs/wps/lib/python3.8/site-packages/pywps/app/Process.py", line 249, in _run_process
    self.handler(wps_request, wps_response)  # the user must update the wps_response.
  File "/opt/wps/raven/processes/wps_climatology_esp.py", line 92, in _handler
    qsims = forecasting.perform_climatology_esp(
  File "/opt/conda/envs/wps/lib/python3.8/site-packages/ravenpy/utilities/forecasting.py", line 103, in perform_climatology_esp
    m = get_model(model_name)(workdir=workdir)
  File "/opt/conda/envs/wps/lib/python3.8/site-packages/ravenpy/models/emulators.py", line 49, in __init__
    super().__init__(*args, **kwds)
  File "/opt/conda/envs/wps/lib/python3.8/site-packages/ravenpy/models/base.py", line 104, in __init__
    raise RuntimeError(
RuntimeError: Could not find raven binary in PATH, and RAVENPY_RAVEN_BINARY_PATH env variable is not set
```