docs: fix doc build failure due to missing executable since not real install
WARNING: autodoc: failed to import process 'processes.RavenProcess' from module 'raven'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/conda/fix-rtd-build-with-smaller-env-yml/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 36, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pavics-raven/checkouts/fix-rtd-build-with-smaller-env-yml/raven/__init__.py", line 15, in <module>
    raise IOError("The raven executable is not installed.")
OSError: The raven executable is not installed.