.travis.yml: conda activate do not work, use conda run -n envname instead
```
$ /home/travis/miniconda3/bin/conda activate raven
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

To initialize your shell, run
    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```