docker: set LD_LIBRARY_PATH to find libnetcdf.so.13
/tmp/pywps_process_hz5_t84d/exec/model/p00/raven: error while loading
shared libraries: libnetcdf.so.13: cannot open shared object file: No
such file or directory

(base) root@096b570e8a16:/# find -iname *libnetcdf.so*
./usr/lib/x86_64-linux-gnu/libnetcdf.so.11.4.0
./usr/lib/x86_64-linux-gnu/libnetcdf.so
./usr/lib/x86_64-linux-gnu/libnetcdf.so.11
./opt/conda/pkgs/libnetcdf-4.6.2-hbdf4f91_1001/lib/libnetcdf.so
./opt/conda/pkgs/libnetcdf-4.6.2-hbdf4f91_1001/lib/libnetcdf.so.13
./opt/conda/envs/wps/lib/libnetcdf.so.13
./opt/conda/envs/wps/lib/libnetcdf.so

Did tried to not install libnetcdf-dev in the docker image which will
not add the libnetcdf.so.11 file but it didn't work.

Had to resort to the LD_LIBRARY_PATH trick.

At this stage, the docker image is probably functional and just need
proper configurations to work.

Launching the container this way:
  docker run --rm --name raven -p 9099:9099 raven

And trying all the notebooks under docs/source/notebooks have the
following results which look like configuration problems:

running_OSTRICH_hmets, running_mohyse, running_hmets, running_gr4jcn,
running_hbv_ec, multi_model_simulation:

ConnectionError: HTTPConnectionPool(host='localhost', port=9099): Max retries
exceeded with url: /outputs/2b5eeecc-78cf-11e9-9343-0242ac110003/OstOutput0.txt
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at
0x7f1c59a04a58>: Failed to establish a new connection: [Errno 111] Connection
refused',))

computing_objective_functions

INFO: _internal._log(): 127.0.0.1 - - [17/May/2019 18:23:26] "GET
/outputs/a906ea86-78d0-11e9-a3b3-0242ac110003/raven-gr4j-cemaneige-sim-0_Hydrographs.nc
HTTP/1.1" 200 -
ERROR: exceptions.__init__(): Exception: code: 400, locator: File size for
input ? exceeded. Maximum allowed: 209715200.0 megabytes, description:

Delineation_workflow

WARNING: utils.generic_extract_archive(): No archives found. Continuing...
/opt/wps/raven/processes/wps_hydrobasins_shape_selection.py:101:
FionaDeprecationWarning: Collection.__next__() is buggy and will be removed in
Fiona 2.0. Switch to `next(iter(collection))`.
  feat = next(src)
WARNING: collection.schema(): Skipping field bbox: invalid type 3
ERROR: collection.__init__(): /tmp/pywps_process_i8whkkaq/hybas_stiw953g.json: No such file or directory
WARNING: collection.__init__(): driver GeoJSON does not support creation option ENCODING
ERROR: collection.__init__(): /tmp/pywps_process_i8whkkaq/hybas_m3gvxym6.json: No such file or directory
WARNING: collection.__init__(): driver GeoJSON does not support creation option ENCODING